### PR TITLE
Make distance filter higher, to reduce battery usage

### PR DESCRIPTION
**Pull request by AndrewSB**
Thanks Felix ❤️

img_2202

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thanks for contributing 👍  Do you think that will fix the battery usage?

**Comment by KrauseFx** [comment]
I pushed a new TestFlight release for this

**Comment by AndrewSB** [comment]
I hope so, I feel as if a majority of the battery is used because the
system is waking up the app in the background every time the device thinks
it moved *25 meters*, which means it will get fired when it enters/leaves
wifi, cellular conditions change, and even probably when I walk from one
end of my apartment of the other.
Every wake up also leads to firebase being re-inited and the app staying
awake long enough to upload the new geopoint, so...

Once I install the update, I'll see whether the usage decreases at all and
respond here 😊

**Comment by KrauseFx** [comment]
Cool, thanks 👍

**Comment by AndrewSB** [comment]
Update: I think we did it 🎉🎉 

wwdc.family is now using about the same amount of energy as moves, which is a pretty good benchmark imo

fullsizeoutput_157d

**Comment by KrauseFx** [comment]
That's awesome, thanks 👍

**Pull request merged**
