### PR TITLE
App Icon & Licensing

### PR DESCRIPTION
**Pull request by joalbright**

### CODE REVIEW

**Comment by KrauseFx** [comment]
This is beautiful, thank you so much ❤️

**Comment by KrauseFx** [comment]
For reference, the other app icons https://twitter.com/Joalbright/status/851230360713265152

**Comment by 3lvis** [comment]
@joalbright Great work! Could you add the Sketch file to https://github.com/wwdc-family/design, please?

**Comment by joalbright** [comment]
@3lvis Gladly.

**Pull request merged**
